AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambdapmt2

  Sample SAM Template for lambdapmt2

Globals:
  Function:
    Timeout: 3

Resources:
  LambdaPmt2:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Role: arn:aws:iam::084534280195:role/edet-lambda-rds-fullaccess
      FunctionName: LambdaPmt2
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./lambdapmt2
      Dockerfile: Dockerfile

Outputs:
  LambdaPmt2:
    Description: "LambdaPmt2"
    Value: !GetAtt LambdaPmt2.Arn
